/* Question bank for the "Tree of Knowledge" minigame.
   Entry shape: [ qEN, qHU, [answersEN], [answersHU], category ]
   The FIRST answer is always the correct one — the runtime shuffles
   them per question, so the source stays easy to read and extend. */
var QUIZ_BANK = {
easy: [
['Which mob explodes when it gets close to you?','Melyik mob robban fel, ha közel ér hozzád?',
 ['Creeper','Zombie','Skeleton','Villager'],['Creeper','Zombi','Csontváz','Falusi'],'mc'],
['What is the weakest pickaxe that can mine diamond ore?','Mi a leggyengébb csákány, amivel gyémántércet lehet bányászni?',
 ['Iron pickaxe','Wooden pickaxe','Stone pickaxe','Golden pickaxe'],['Vas csákány','Fa csákány','Kő csákány','Arany csákány'],'mc'],
['How many blocks fit in a full stack of cobblestone?','Hány blokk fér egy teli stack kőbe (cobblestone)?',
 ['64','16','32','100'],['64','16','32','100'],'mc'],
['Which dimension do you reach through an obsidian portal?','Melyik dimenzióba jutsz egy obszidián portálon át?',
 ['The Nether','The End','The Aether','The Void'],['A Nether','Az End','Az Aether','A Void'],'mc'],
['What do sheep drop when you shear them?','Mit adnak a bárányok, ha megnyírod őket?',
 ['Wool','Leather','String','Feathers'],['Gyapjút','Bőrt','Fonalat','Tollat'],'mc'],
['Which hostile mob teleports away when you look at it?','Melyik ellenséges mob teleportál el, ha ránézel?',
 ['Enderman','Creeper','Blaze','Witch'],['Enderman','Creeper','Blaze','Boszorkány'],'mc'],
['What can you use to set off TNT?','Mivel lehet felrobbantani a TNT-t?',
 ['Flint and steel','A water bucket','Shears','Bone meal'],['Kova és acél','Vödör víz','Olló','Csontliszt'],'mc'],
['Which block cannot be broken in survival mode?','Melyik blokkot nem lehet survival módban elbontani?',
 ['Bedrock','Obsidian','Ancient debris','Netherite block'],['Bedrock','Obszidián','Ancient debris','Netherite blokk'],'mc'],
['What two items craft a torch?','Melyik két tárgyból készül a fáklya?',
 ['Stick and coal','Stick and iron','Stick and redstone','Stick and flint'],['Bot és szén','Bot és vas','Bot és redstone','Bot és kova'],'mc'],
['Which food is made from wheat?','Melyik étel készül búzából?',
 ['Bread','Steak','Baked potato','Golden apple'],['Kenyér','Steak','Sült krumpli','Aranyalma'],'mc'],
['What is the name of the boss in the End?','Mi a neve az End főellenségének?',
 ['Ender Dragon','The Wither','The Warden','Elder Guardian'],['Ender Dragon','Wither','Warden','Elder Guardian'],'mc'],
['How many hearts of health does a player have?','Hány szív életereje van egy játékosnak?',
 ['10','20','5','15'],['10','20','5','15'],'mc'],
['Which Minecraft edition runs on consoles and phones?','Melyik Minecraft kiadás fut konzolon és telefonon?',
 ['Bedrock Edition','Java Edition','Classic','Education Edition'],['Bedrock Edition','Java Edition','Classic','Education Edition'],'mc'],
['Who originally created Minecraft?','Ki készítette eredetileg a Minecraftot?',
 ['Markus "Notch" Persson','Gabe Newell','Hideo Kojima','Shigeru Miyamoto'],['Markus „Notch” Persson','Gabe Newell','Hideo Kojima','Shigeru Miyamoto'],'mc'],
['Which company owns Minecraft today?','Melyik cég tulajdonában van ma a Minecraft?',
 ['Microsoft','Sony','Epic Games','Valve'],['Microsoft','Sony','Epic Games','Valve'],'mc'],
['What is a plugin on a Minecraft server?','Mi az a plugin egy Minecraft szerveren?',
 ['An add-on that adds new features','The name of a block','A player rank','A world type'],['Egy kiegészítő, ami új funkciókat ad','Egy blokk neve','Egy játékosrang','Egy világtípus'],'mc'],
['Which platform do Minecraft communities mostly use for chat?','Melyik platformot használják leginkább a Minecraft közösségek?',
 ['Discord','LinkedIn','Pinterest','Tumblr'],['Discord','LinkedIn','Pinterest','Tumblr'],'mc'],
['What does AFK mean?','Mit jelent az AFK?',
 ['Away from keyboard','Attack from keyboard','All for kill','Auto farm kit'],['Away from keyboard – nem vagyok a gépnél','Attack from keyboard','All for kill','Auto farm kit'],'mc'],
['Which item do you need to open the End portal?','Milyen tárgy kell az End portál megnyitásához?',
 ['Eyes of Ender','Blaze rods','Nether star','Diamonds'],['Ender szem','Blaze rúd','Nether csillag','Gyémánt'],'mc'],
['Which mob shoots arrows at you at night?','Melyik mob lő rád nyilakkal éjszaka?',
 ['Skeleton','Zombie','Slime','Silverfish'],['Csontváz','Zombi','Slime','Silverfish'],'mc'],

['What does HTML stand for?','Mit jelent a HTML rövidítés?',
 ['HyperText Markup Language','Home Tool Markup Language','Hyperlink Text Making Language','High Transfer Machine Language'],['HyperText Markup Language','Home Tool Markup Language','Hyperlink Text Making Language','High Transfer Machine Language'],'dev'],
['Which language is used to style a web page?','Melyik nyelvvel formázzuk egy weboldal kinézetét?',
 ['CSS','Python','SQL','Java'],['CSS','Python','SQL','Java'],'dev'],
['What does the "S" in HTTPS stand for?','Mit jelent az „S” a HTTPS-ben?',
 ['Secure','Simple','Standard','Static'],['Secure – biztonságos','Simple','Standard','Static'],'dev'],
['Which character starts an id selector in CSS?','Melyik karakterrel kezdődik egy id szelektor CSS-ben?',
 ['#','.','@','$'],['#','.','@','$'],'dev'],
['Which HTML tag creates a link?','Melyik HTML tag hoz létre linket?',
 ['<a>','<link>','<href>','<url>'],['<a>','<link>','<href>','<url>'],'dev'],
['What is Git used for?','Mire használjuk a Gitet?',
 ['Version control','Image editing','Web hosting','Database backups'],['Verziókezelésre','Képszerkesztésre','Webtárhelyre','Adatbázis-mentésre'],'dev'],
['What does the error code 404 mean?','Mit jelent a 404-es hibakód?',
 ['Page not found','Server error','Access denied','Too many requests'],['Az oldal nem található','Szerverhiba','Hozzáférés megtagadva','Túl sok kérés'],'dev'],
['Which of these is a JavaScript library or framework?','Az alábbiak közül melyik JavaScript könyvtár vagy keretrendszer?',
 ['React','Laravel','Django','Rails'],['React','Laravel','Django','Rails'],'dev'],
['What does IP stand for in "IP address"?','Mit jelent az IP az „IP-cím”-ben?',
 ['Internet Protocol','Internal Process','Internet Provider','Instant Ping'],['Internet Protocol','Internal Process','Internet Provider','Instant Ping'],'dev'],
['What does CPU stand for?','Mit jelent a CPU rövidítés?',
 ['Central Processing Unit','Computer Power Unit','Central Program Utility','Core Peripheral Unit'],['Central Processing Unit – központi feldolgozóegység','Computer Power Unit','Central Program Utility','Core Peripheral Unit'],'dev'],
['How many bits are in one byte?','Hány bit van egy bájtban?',
 ['8','4','16','32'],['8','4','16','32'],'dev'],
['Which company develops Java today?','Melyik cég fejleszti ma a Javát?',
 ['Oracle','Microsoft','Google','Apple'],['Oracle','Microsoft','Google','Apple'],'dev'],
['What does a browser do with HTML?','Mit csinál a böngésző a HTML-lel?',
 ['Renders it as a page','Compiles it to machine code','Encrypts it','Stores it in a database'],['Oldalként megjeleníti','Gépi kódra fordítja','Titkosítja','Adatbázisba menti'],'dev'],
['Which file extension do JavaScript files use?','Milyen kiterjesztést használnak a JavaScript fájlok?',
 ['.js','.jv','.jsc','.java'],['.js','.jv','.jsc','.java'],'dev'],
['What is a "bug" in programming?','Mi az a „bug” a programozásban?',
 ['An error in the code','A finished feature','A type of server','A code comment'],['Egy hiba a kódban','Egy kész funkció','Egy szervertípus','Egy kódkomment'],'dev'],

['What is the capital of Hungary?','Mi Magyarország fővárosa?',
 ['Budapest','Debrecen','Szeged','Miskolc'],['Budapest','Debrecen','Szeged','Miskolc'],'gen'],
['Which river flows through Budapest?','Melyik folyó folyik át Budapesten?',
 ['The Danube','The Tisza','The Rhine','The Vistula'],['A Duna','A Tisza','A Rajna','A Visztula'],'gen'],
['What is the currency of Hungary?','Mi Magyarország pénzneme?',
 ['Forint','Euro','Koruna','Zloty'],['Forint','Euró','Korona','Zloty'],'gen'],
['What are the colours of the Hungarian flag, from top to bottom?','Milyen színű a magyar zászló, fentről lefelé?',
 ['Red, white, green','Green, white, red','Red, green, white','White, red, green'],['Piros, fehér, zöld','Zöld, fehér, piros','Piros, zöld, fehér','Fehér, piros, zöld'],'gen'],
['Which planet is known as the Red Planet?','Melyik bolygót hívják vörös bolygónak?',
 ['Mars','Venus','Jupiter','Mercury'],['Mars','Vénusz','Jupiter','Merkúr'],'gen'],
['What is the chemical formula of water?','Mi a víz kémiai képlete?',
 ['H2O','CO2','O2','NaCl'],['H2O','CO2','O2','NaCl'],'gen'],
['How many minutes are there in a full day?','Hány perc van egy teljes napban?',
 ['1440','1200','2400','960'],['1440','1200','2400','960'],'gen'],
['Which is the largest ocean on Earth?','Melyik a Föld legnagyobb óceánja?',
 ['The Pacific','The Atlantic','The Indian','The Arctic'],['A Csendes-óceán','Az Atlanti-óceán','Az Indiai-óceán','A Jeges-tenger'],'gen'],
['How many sides does a hexagon have?','Hány oldala van egy hatszögnek?',
 ['6','5','7','8'],['6','5','7','8'],'gen'],
['What is the chemical symbol for gold?','Mi az arany vegyjele?',
 ['Au','Ag','Go','Gd'],['Au','Ag','Go','Gd'],'gen'],
['Which star is closest to Earth?','Melyik csillag van a legközelebb a Földhöz?',
 ['The Sun','Proxima Centauri','Sirius','Betelgeuse'],['A Nap','Proxima Centauri','Szíriusz','Betelgeuse'],'gen'],
['At sea level, at how many degrees Celsius does water boil?','Tengerszinten hány Celsius-fokon forr a víz?',
 ['100','90','120','80'],['100','90','120','80'],'gen'],
['Which continent is Hungary on?','Melyik kontinensen fekszik Magyarország?',
 ['Europe','Asia','Africa','South America'],['Európa','Ázsia','Afrika','Dél-Amerika'],'gen'],
['How many players from one team are on a football pitch?','Hány játékos van egy csapatból a futballpályán?',
 ['11','10','9','12'],['11','10','9','12'],'gen'],
['What is the largest animal on Earth?','Mi a Föld legnagyobb állata?',
 ['The blue whale','The African elephant','The giraffe','The great white shark'],['A kék bálna','Az afrikai elefánt','A zsiráf','A nagy fehér cápa'],'gen'],
['Which gas do plants take in for photosynthesis?','Melyik gázt veszik fel a növények a fotoszintézishez?',
 ['Carbon dioxide','Oxygen','Nitrogen','Helium'],['Szén-dioxidot','Oxigént','Nitrogént','Héliumot'],'gen'],

['Which tool digs sand and gravel the fastest?','Melyik eszközzel lehet leggyorsabban homokot és kavicsot ásni?',
 ['Shovel','Pickaxe','Axe','Hoe'],['Ásó','Csákány','Balta','Kapa'],'mc'],
['Which tool chops wood the fastest?','Melyik eszközzel lehet leggyorsabban fát vágni?',
 ['Axe','Pickaxe','Shovel','Sword'],['Balta','Csákány','Ásó','Kard'],'mc'],
['What block makes you bounce when you land on it?','Melyik blokkon pattansz, ha ráesel?',
 ['Slime block','Honey block','Hay bale','Sponge'],['Slime blokk','Mézblokk','Szénabála','Szivacs'],'mc'],
['What do you need to tame a wolf?','Mivel lehet megszelídíteni egy farkast?',
 ['Bones','Wheat','Carrots','Seeds'],['Csonttal','Búzával','Répával','Maggal'],'mc'],
['What happens to a torch placed under water?','Mi történik a víz alá tett fáklyával?',
 ['It breaks off','It keeps burning','It turns blue','Nothing at all'],['Letörik','Tovább ég','Kékre vált','Semmi'],'mc'],
['Which of these animals can you ride with a saddle?','Az alábbi állatok közül melyikre lehet nyereggel felülni?',
 ['Pig','Cow','Chicken','Sheep'],['Malacra','Tehénre','Csirkére','Bárányra'],'mc'],
['What does bone meal do to a crop?','Mit csinál a csontliszt a növényekkel?',
 ['Makes it grow instantly','Kills it','Turns it into dirt','Nothing'],['Azonnal megnöveszti','Elpusztítja','Földdé változtatja','Semmit'],'mc'],
['How many planks does a crafting table take?','Hány deszkából készül a munkaasztal?',
 ['4','8','2','6'],['4','8','2','6'],'mc'],
['Which item lets you go fishing?','Melyik tárggyal lehet horgászni?',
 ['Fishing rod','Bucket','Trident','Shears'],['Horgászbottal','Vödörrel','Tridenttel','Ollóval'],'mc'],
['What does sleeping in a bed at night do?','Mit csinál az ágyban alvás éjszaka?',
 ['Skips to morning','Fully heals you','Saves your items','Summons mobs'],['Reggelre ugrik','Teljesen meggyógyít','Elmenti a tárgyaidat','Mobokat idéz'],'mc'],

['What does the HTTP status code 200 mean?','Mit jelent a 200-as HTTP státuszkód?',
 ['OK — the request succeeded','Not found','Redirect','Server error'],['OK — a kérés sikeres','Nem található','Átirányítás','Szerverhiba'],'dev'],
['Which of these is a code editor?','Az alábbiak közül melyik kódszerkesztő?',
 ['Visual Studio Code','Photoshop','Excel','Blender'],['Visual Studio Code','Photoshop','Excel','Blender'],'dev'],
['What is a variable in programming?','Mi az a változó a programozásban?',
 ['A named place that stores a value','A kind of loop','A file format','A type of bug'],['Egy névvel ellátott hely, ami értéket tárol','Egy ciklusfajta','Egy fájlformátum','Egy hibatípus'],'dev'],
['What does "localhost" refer to?','Mire utal a „localhost”?',
 ['Your own machine','A public web server','A DNS provider','A content delivery network'],['A saját gépedre','Egy nyilvános webszerverre','Egy DNS szolgáltatóra','Egy tartalomszolgáltató hálózatra'],'dev'],
['Which language are Spigot plugins mainly written in?','Milyen nyelven írják jellemzően a Spigot pluginokat?',
 ['Java','Python','Lua','C++'],['Java','Python','Lua','C++'],'dev'],
['What does FTP stand for?','Mit jelent az FTP rövidítés?',
 ['File Transfer Protocol','Fast Transfer Path','Full Text Parser','File Type Provider'],['File Transfer Protocol','Fast Transfer Path','Full Text Parser','File Type Provider'],'dev'],
['What is a repository in Git?','Mi az a repository Gitben?',
 ['A tracked project folder with its history','A server rack','A code editor','A backup drive'],['Egy verziókövetett projektmappa a történetével','Egy szerverszekrény','Egy kódszerkesztő','Egy mentési meghajtó'],'dev'],
['What does "open source" mean?','Mit jelent az „open source”?',
 ['The source code is publicly available','The software is always free of bugs','It only runs on Linux','It has no licence at all'],['A forráskód nyilvánosan elérhető','A szoftver mindig hibamentes','Csak Linuxon fut','Nincs rajta semmilyen licenc'],'dev'],
['Which is bigger, a megabyte or a kilobyte?','Melyik a nagyobb: megabájt vagy kilobájt?',
 ['A megabyte','A kilobyte','They are equal','It depends on the file'],['A megabájt','A kilobájt','Egyformák','A fájltól függ'],'dev'],
['Which character separates the domain from the path in a URL?','Melyik karakter választja el a domaint az útvonaltól egy URL-ben?',
 ['/','?','#',':'],['/','?','#',':'],'dev'],

['How many days are in a leap year?','Hány nap van egy szökőévben?',
 ['366','365','364','367'],['366','365','364','367'],'gen'],
['Which is the largest planet in the Solar System?','Melyik a Naprendszer legnagyobb bolygója?',
 ['Jupiter','Saturn','Neptune','Earth'],['A Jupiter','A Szaturnusz','A Neptunusz','A Föld'],'gen'],
['Which organ pumps blood around the body?','Melyik szerv pumpálja a vért a testben?',
 ['The heart','The liver','The lungs','The kidney'],['A szív','A máj','A tüdő','A vese'],'gen'],
['How many letters does the English alphabet have?','Hány betűből áll az angol ábécé?',
 ['26','24','28','30'],['26','24','28','30'],'gen'],
['At how many degrees Celsius does water freeze?','Hány Celsius-fokon fagy meg a víz?',
 ['0','-10','4','10'],['0','-10','4','10'],'gen'],
['What does WWW stand for?','Mit jelent a WWW rövidítés?',
 ['World Wide Web','Wide World Web','World Web Wire','Web Wide World'],['World Wide Web','Wide World Web','World Web Wire','Web Wide World'],'gen'],
['Which is the fastest land animal?','Melyik a leggyorsabb szárazföldi állat?',
 ['The cheetah','The lion','The horse','The greyhound'],['A gepárd','Az oroszlán','A ló','Az agár'],'gen'],
['How many hours are in a week?','Hány óra van egy hétben?',
 ['168','148','180','156'],['168','148','180','156'],'gen'],
['What is the capital of Austria?','Mi Ausztria fővárosa?',
 ['Vienna','Salzburg','Graz','Linz'],['Bécs','Salzburg','Graz','Linz'],'gen'],
['How many counties does Hungary have?','Hány vármegyéje van Magyarországnak?',
 ['19','14','23','9'],['19','14','23','9'],'gen']
],

medium: [
['What is the minimum number of obsidian blocks for a working Nether portal?','Minimum hány obszidián blokk kell egy működő Nether portálhoz?',
 ['10','14','12','8'],['10','14','12','8'],'mc'],
['What is the highest level of Sharpness in vanilla survival?','Mi a Sharpness legmagasabb szintje vanilla survivalben?',
 ['V','IV','VI','X'],['V','IV','VI','X'],'mc'],
['Which mob drops blaze rods?','Melyik mob ejt blaze rudat?',
 ['Blaze','Wither Skeleton','Ghast','Magma Cube'],['Blaze','Wither csontváz','Ghast','Magma Cube'],'mc'],
['What do you combine with netherite scrap to get a netherite ingot?','Mivel kell kombinálni a netherite scrapet, hogy netherite rudat kapj?',
 ['Gold ingots','Iron ingots','Diamonds','Quartz'],['Aranyrúddal','Vasrúddal','Gyémánttal','Kvarccal'],'mc'],
['What does the Silk Touch enchantment do?','Mit csinál a Silk Touch varázslat?',
 ['Drops the block itself instead of its usual drop','Makes mining faster','Doubles the drops','Repairs the tool'],['Magát a blokkot ejti a szokásos drop helyett','Gyorsabbá teszi a bányászást','Duplázza a dropot','Javítja az eszközt'],'mc'],
['Which ingredient brews a Night Vision potion?','Melyik hozzávalóból készül a Night Vision bájital?',
 ['Golden carrot','Spider eye','Sugar','Magma cream'],['Aranyrépából','Pókszemből','Cukorból','Magmakrémből'],'mc'],
['How many Eyes of Ender does a completely empty End portal need?','Hány Ender szem kell egy teljesen üres End portálhoz?',
 ['12','10','8','16'],['12','10','8','16'],'mc'],
['What sense does the Warden hunt by?','Milyen érzékkel vadászik a Warden?',
 ['Vibration and sound','Sight','Smell','Light level'],['Rezgéssel és hanggal','Látással','Szaglással','Fényszint alapján'],'mc'],
['Which redstone component restores a signal to full strength?','Melyik redstone elem állítja vissza teljes erősségre a jelet?',
 ['Repeater','Comparator','Observer','Dropper'],['Repeater','Comparator','Observer','Dropper'],'mc'],
['Which villager profession trades enchanted books?','Melyik falusi szakma ad varázsolt könyvet cserébe?',
 ['Librarian','Farmer','Butcher','Nitwit'],['Könyvtáros','Földműves','Hentes','Nitwit'],'mc'],
['What does the Wither drop when defeated?','Mit ejt a Wither, ha legyőzöd?',
 ['A Nether star','A dragon egg','A totem of undying','An elytra'],['Nether csillagot','Sárkánytojást','Totem of undyingot','Elytrát'],'mc'],
['Where can you find elytra?','Hol találsz elytrát?',
 ['End cities','Nether fortresses','Ocean monuments','Woodland mansions'],['End városokban','Nether erődökben','Óceáni monumentumokban','Woodland kastélyokban'],'mc'],
['What is the build height limit since Minecraft 1.18?','Mennyi az építési magassági határ a Minecraft 1.18 óta?',
 ['320','256','128','384'],['320','256','128','384'],'mc'],
['Which mob can drop a Totem of Undying?','Melyik mob ejthet Totem of Undyingot?',
 ['Evoker','Pillager','Vindicator','Witch'],['Evoker','Pillager','Vindicator','Boszorkány'],'mc'],
['How many game ticks make up one second?','Hány game tick van egy másodpercben?',
 ['20','10','60','30'],['20','10','60','30'],'mc'],

['Which HTTP status code means "Internal Server Error"?','Melyik HTTP státuszkód jelenti azt, hogy „Internal Server Error”?',
 ['500','404','403','301'],['500','404','403','301'],'dev'],
['What does API stand for?','Mit jelent az API rövidítés?',
 ['Application Programming Interface','Applied Program Input','Automatic Process Integration','Advanced Protocol Index'],['Application Programming Interface','Applied Program Input','Automatic Process Integration','Advanced Protocol Index'],'dev'],
['Which data format uses curly braces and key-value pairs?','Melyik adatformátum használ kapcsos zárójeleket és kulcs-érték párokat?',
 ['JSON','CSV','YAML','INI'],['JSON','CSV','YAML','INI'],'dev'],
['What does SQL stand for?','Mit jelent az SQL rövidítés?',
 ['Structured Query Language','Simple Query Logic','Server Question Language','Standard Quick Lookup'],['Structured Query Language','Simple Query Logic','Server Question Language','Standard Quick Lookup'],'dev'],
['Which port does HTTPS use by default?','Melyik portot használja alapból a HTTPS?',
 ['443','80','8080','22'],['443','80','8080','22'],'dev'],
['What is the default port of a Minecraft Java server?','Mi egy Minecraft Java szerver alapértelmezett portja?',
 ['25565','19132','25575','8080'],['25565','19132','25575','8080'],'dev'],
['Which of these is a relational database?','Az alábbiak közül melyik relációs adatbázis?',
 ['MySQL','MongoDB','Redis','Cassandra'],['MySQL','MongoDB','Redis','Cassandra'],'dev'],
['What does "responsive design" mean?','Mit jelent a „reszponzív design”?',
 ['The layout adapts to the screen size','The site loads quickly','The server replies fast','The site works offline'],['Az elrendezés alkalmazkodik a képernyőmérethez','Az oldal gyorsan betölt','A szerver gyorsan válaszol','Az oldal offline is működik'],'dev'],
['In Git, which command uploads your commits to a remote?','Gitben melyik parancs tölti fel a commitjaidat a távoli tárolóba?',
 ['push','pull','commit','merge'],['push','pull','commit','merge'],'dev'],
['Which of these languages runs natively in the browser?','Az alábbiak közül melyik nyelv fut natívan a böngészőben?',
 ['JavaScript','PHP','Python','C#'],['JavaScript','PHP','Python','C#'],'dev'],
['What is the job of DNS?','Mi a DNS feladata?',
 ['Resolving domain names to IP addresses','Encrypting traffic','Storing website files','Compressing images'],['A domainnevek IP-címre fordítása','A forgalom titkosítása','A weboldal fájljainak tárolása','Képek tömörítése'],'dev'],
['Which Minecraft server software uses the Bukkit plugin API?','Melyik Minecraft szerverszoftver használja a Bukkit plugin API-t?',
 ['Spigot','Forge','Fabric','Vanilla'],['Spigot','Forge','Fabric','Vanilla'],'dev'],
['What does CDN stand for?','Mit jelent a CDN rövidítés?',
 ['Content Delivery Network','Central Data Node','Cached Domain Name','Client Data Network'],['Content Delivery Network','Central Data Node','Cached Domain Name','Client Data Network'],'dev'],
['Which symbol starts a single-line comment in Java?','Melyik jellel kezdődik egy egysoros komment Javában?',
 ['//','#','--','!'],['//','#','--','!'],'dev'],
['In CSS, which property sets the text size?','CSS-ben melyik tulajdonság állítja a szöveg méretét?',
 ['font-size','text-size','font-style','type-scale'],['font-size','text-size','font-style','type-scale'],'dev'],

['Who wrote the lyrics of the Hungarian national anthem?','Ki írta a magyar Himnusz szövegét?',
 ['Ferenc Kölcsey','Sándor Petőfi','János Arany','Mihály Vörösmarty'],['Kölcsey Ferenc','Petőfi Sándor','Arany János','Vörösmarty Mihály'],'gen'],
['In which year did Hungary join the European Union?','Melyik évben csatlakozott Magyarország az Európai Unióhoz?',
 ['2004','1999','2007','2010'],['2004','1999','2007','2010'],'gen'],
['Which is the largest lake in Central Europe?','Melyik Közép-Európa legnagyobb tava?',
 ['Lake Balaton','Lake Constance','Lake Geneva','Lake Neusiedl'],['A Balaton','A Bodeni-tó','A Genfi-tó','A Fertő tó'],'gen'],
['Which element has the symbol Fe?','Melyik elem vegyjele az Fe?',
 ['Iron','Fluorine','Francium','Lead'],['Vas','Fluor','Francium','Ólom'],'gen'],
['How many bones does an adult human body have?','Hány csont van egy felnőtt ember testében?',
 ['206','186','226','250'],['206','186','226','250'],'gen'],
['Roughly how fast does light travel in a vacuum?','Nagyjából milyen gyorsan halad a fény vákuumban?',
 ['300,000 km/s','300,000 m/s','3,000 km/s','30,000 km/s'],['300 000 km/s','300 000 m/s','3 000 km/s','30 000 km/s'],'gen'],
['Which planet has the Great Red Spot?','Melyik bolygón található a Nagy Vörös Folt?',
 ['Jupiter','Saturn','Mars','Neptune'],['Jupiter','Szaturnusz','Mars','Neptunusz'],'gen'],
['What is the decimal number 8 in binary?','Mi a 8-as szám kettes számrendszerben?',
 ['1000','100','1010','110'],['1000','100','1010','110'],'gen'],
['In which year did the Berlin Wall fall?','Melyik évben omlott le a berlini fal?',
 ['1989','1991','1987','1990'],['1989','1991','1987','1990'],'gen'],
['Who painted the Mona Lisa?','Ki festette a Mona Lisát?',
 ['Leonardo da Vinci','Michelangelo','Raphael','Sandro Botticelli'],['Leonardo da Vinci','Michelangelo','Raffaello','Sandro Botticelli'],'gen'],
['What is the highest mountain peak in Hungary?','Mi Magyarország legmagasabb hegycsúcsa?',
 ['Kékes','Írott-kő','Dobogókő','Nagy-Milic'],['A Kékes','Az Írott-kő','A Dobogókő','A Nagy-Milic'],'gen'],
['How many keys does a standard piano have?','Hány billentyűje van egy standard zongorának?',
 ['88','76','61','96'],['88','76','61','96'],'gen'],
['What does RAM stand for?','Mit jelent a RAM rövidítés?',
 ['Random Access Memory','Rapid Active Memory','Read Access Module','Runtime Allocated Memory'],['Random Access Memory','Rapid Active Memory','Read Access Module','Runtime Allocated Memory'],'gen'],
['Which country does the inventor of the Rubik\'s Cube come from?','Melyik országból származik a Rubik-kocka feltalálója?',
 ['Hungary','Czechia','Poland','Austria'],['Magyarországról','Csehországból','Lengyelországból','Ausztriából'],'gen'],
['Which sea does the Danube flow into?','Melyik tengerbe ömlik a Duna?',
 ['The Black Sea','The Adriatic Sea','The Baltic Sea','The North Sea'],['A Fekete-tengerbe','Az Adriai-tengerbe','A Balti-tengerbe','Az Északi-tengerbe'],'gen'],

['How many diamonds does a full set of diamond armour cost?','Hány gyémánt kell egy teljes gyémánt páncélkészlethez?',
 ['24','18','30','12'],['24','18','30','12'],'mc'],
['What does the Mending enchantment repair an item with?','Mivel javítja a tárgyat a Mending varázslat?',
 ['Experience orbs','Iron ingots','Emeralds','Redstone'],['Tapasztalati gömbökkel','Vasrúddal','Smaragddal','Redstone-nal'],'mc'],
['How many planks does a chest take?','Hány deszkából készül egy láda?',
 ['8','6','4','10'],['8','6','4','10'],'mc'],
['What does Fortune III increase on an ore?','Mit növel a Fortune III az érceknél?',
 ['The number of items dropped','The mining speed','The tool durability','The experience gained'],['Az ejtett tárgyak számát','A bányászás sebességét','Az eszköz tartósságát','A kapott tapasztalatot'],'mc'],
['Which structure contains the End portal?','Melyik struktúra rejti az End portált?',
 ['A stronghold','A woodland mansion','An ocean monument','A desert temple'],['Az erődítmény (stronghold)','A woodland kastély','Az óceáni monumentum','A sivatagi templom'],'mc'],
['What is the highest enchantment level an enchanting table can offer?','Mi a legmagasabb varázslási szint, amit a varázsasztal kínálhat?',
 ['30','25','50','15'],['30','25','50','15'],'mc'],
['How many bookshelves does a fully powered enchanting table need?','Hány könyvespolc kell egy teljesen feltöltött varázsasztalhoz?',
 ['15','12','20','9'],['15','12','20','9'],'mc'],
['What happens to a creeper hit by lightning?','Mi történik egy villámcsapás érte creeperrel?',
 ['It becomes charged','It dies instantly','It turns friendly','It drops diamonds'],['Feltöltötté (charged) válik','Azonnal meghal','Barátságos lesz','Gyémántot ejt'],'mc'],
['Which block can push other blocks?','Melyik blokk tud más blokkokat tolni?',
 ['Piston','Dispenser','Observer','Hopper'],['A piston','A dispenser','Az observer','A hopper'],'mc'],
['What do three wool and three planks craft?','Mi készül három gyapjúból és három deszkából?',
 ['A bed','A loom','A banner','A painting'],['Egy ágy','Egy szövőszék','Egy zászló','Egy festmény'],'mc'],
['What happens to water placed in the Nether?','Mi történik a Netherben kiöntött vízzel?',
 ['It evaporates instantly','It freezes','It turns into lava','It flows normally'],['Azonnal elpárolog','Megfagy','Lávává válik','Normálisan folyik'],'mc'],
['At which light level can hostile mobs spawn in the Overworld in Java Edition?','Milyen fényszinten spawnolhatnak ellenséges mobok az Overworldben Java Editionben?',
 ['0','7','4','11'],['0','7','4','11'],'mc'],

['What does the viewport meta tag control?','Mit szabályoz a viewport meta tag?',
 ['How the page scales on mobile screens','The page background colour','The favicon','The page title'],['Hogyan skálázódik az oldal mobilon','Az oldal háttérszínét','A faviconját','Az oldal címét'],'dev'],
['Which HTTP method normally submits a form with data?','Melyik HTTP metódussal küldünk be általában adatot tartalmazó űrlapot?',
 ['POST','GET','HEAD','OPTIONS'],['POST','GET','HEAD','OPTIONS'],'dev'],
['In JavaScript, what does === check that == does not?','JavaScriptben mit ellenőriz a === , amit a == nem?',
 ['The type of the values','The order of the values','The variable names','The memory address'],['Az értékek típusát','Az értékek sorrendjét','A változóneveket','A memóriacímet'],'dev'],
['What is a database index for?','Mire való az adatbázis-index?',
 ['Speeding up lookups','Encrypting the data','Backing up the table','Formatting the output'],['A keresések gyorsítására','Az adatok titkosítására','A tábla mentésére','A kimenet formázására'],'dev'],
['Which protocol sends email?','Melyik protokoll küldi az e-mailt?',
 ['SMTP','IMAP','FTP','SSH'],['SMTP','IMAP','FTP','SSH'],'dev'],
['What does it mean to "minify" a file?','Mit jelent egy fájl „minifikálása”?',
 ['Stripping whitespace and shortening names to shrink it','Encrypting it','Splitting it into parts','Converting it to binary'],['A felesleges szóközök és hosszú nevek eltávolítása a méret csökkentéséhez','A titkosítása','A darabokra bontása','Binárissá alakítása'],'dev'],
['What is RCON used for on a Minecraft server?','Mire használják az RCON-t egy Minecraft szerveren?',
 ['Running console commands remotely','Storing player data','Rendering the map','Limiting bandwidth'],['Konzolparancsok távoli futtatására','A játékosadatok tárolására','A térkép renderelésére','A sávszélesség korlátozására'],'dev'],
['Which file declares a Spigot plugin\'s name and main class?','Melyik fájl adja meg egy Spigot plugin nevét és fő osztályát?',
 ['plugin.yml','config.yml','server.properties','pom.xml'],['plugin.yml','config.yml','server.properties','pom.xml'],'dev'],
['What does the HTTP status code 301 mean?','Mit jelent a 301-es HTTP státuszkód?',
 ['Moved permanently','Created','Bad request','Gateway timeout'],['Véglegesen áthelyezve','Létrehozva','Hibás kérés','Átjáró időtúllépés'],'dev'],
['Which CSS layout system defines rows and columns explicitly?','Melyik CSS elrendezés definiál kifejezetten sorokat és oszlopokat?',
 ['Grid','Flexbox','Float','Position'],['A Grid','A Flexbox','A Float','A Position'],'dev'],
['What does git clone do?','Mit csinál a git clone?',
 ['Copies a remote repository to your machine','Deletes a branch','Uploads your commits','Creates an empty file'],['Letölti a távoli repositoryt a gépedre','Töröl egy branchet','Feltölti a commitjaidat','Üres fájlt hoz létre'],'dev'],
['What does JVM stand for?','Mit jelent a JVM rövidítés?',
 ['Java Virtual Machine','Java Version Manager','Joint Virtual Memory','Java Variable Model'],['Java Virtual Machine','Java Version Manager','Joint Virtual Memory','Java Variable Model'],'dev'],

['Which planet is closest to the Sun?','Melyik bolygó van legközelebb a Naphoz?',
 ['Mercury','Venus','Earth','Mars'],['A Merkúr','A Vénusz','A Föld','A Mars'],'gen'],
['How many strings does a standard guitar have?','Hány húrja van egy hagyományos gitárnak?',
 ['6','4','8','12'],['6','4','8','12'],'gen'],
['In which year did humans first land on the Moon?','Melyik évben szállt le ember először a Holdon?',
 ['1969','1972','1965','1975'],['1969','1972','1965','1975'],'gen'],
['Which is the largest hot desert in the world?','Melyik a világ legnagyobb forró sivataga?',
 ['The Sahara','The Gobi','The Kalahari','The Atacama'],['A Szahara','A Góbi','A Kalahári','Az Atacama'],'gen'],
['What is the official language of Brazil?','Mi Brazília hivatalos nyelve?',
 ['Portuguese','Spanish','Brazilian','French'],['A portugál','A spanyol','A brazil','A francia'],'gen'],
['Which composer wrote the Hungarian Rhapsodies?','Ki szerezte a Magyar rapszódiákat?',
 ['Franz Liszt','Béla Bartók','Zoltán Kodály','Ferenc Erkel'],['Liszt Ferenc','Bartók Béla','Kodály Zoltán','Erkel Ferenc'],'gen'],
['How many players from one team are on a basketball court?','Hány játékos van egy csapatból a kosárlabdapályán?',
 ['5','6','7','4'],['5','6','7','4'],'gen'],
['What is the hardest naturally occurring substance?','Mi a legkeményebb természetes anyag?',
 ['Diamond','Quartz','Steel','Granite'],['A gyémánt','A kvarc','Az acél','A gránit'],'gen'],
['In which year did the Second World War end?','Melyik évben ért véget a második világháború?',
 ['1945','1944','1946','1939'],['1945','1944','1946','1939'],'gen'],
['Which red blood cell type is the universal donor?','Melyik vörösvértest-típus az univerzális donor?',
 ['O negative','AB positive','A positive','B negative'],['A 0 negatív','Az AB pozitív','Az A pozitív','A B negatív'],'gen']
],

hard: [
['How many blocks wide and long is one Minecraft chunk?','Hány blokk széles és hosszú egy Minecraft chunk?',
 ['16 x 16','32 x 32','8 x 8','64 x 64'],['16 x 16','32 x 32','8 x 8','64 x 64'],'mc'],
['How many blocks does a full four-layer beacon pyramid need?','Hány blokk kell egy teljes, négyszintes beacon piramishoz?',
 ['164','144','100','180'],['164','144','100','180'],'mc'],
['What is the Y coordinate of the bedrock floor since 1.18?','Mi a bedrock aljának Y koordinátája 1.18 óta?',
 ['-64','0','-60','-32'],['-64','0','-60','-32'],'mc'],
['Which of these enchantments cannot go on a bow?','Az alábbi varázslatok közül melyik nem tehető íjra?',
 ['Sharpness','Punch','Flame','Infinity'],['Sharpness','Punch','Flame','Infinity'],'mc'],
['How many wither skeleton skulls are needed to summon the Wither?','Hány wither csontvázkoponya kell a Wither megidézéséhez?',
 ['3','4','2','5'],['3','4','2','5'],'mc'],
['In which biome do mooshrooms spawn naturally?','Melyik biomban spawnolnak természetesen a mooshroomok?',
 ['Mushroom fields','Swamp','Dark forest','Jungle'],['Mushroom fields','Mocsár','Sötét erdő','Dzsungel'],'mc'],
['What is the maximum stack size of ender pearls?','Mennyi az ender pearl maximális stackmérete?',
 ['16','64','1','32'],['16','64','1','32'],'mc'],
['What does a comparator in subtract mode do?','Mit csinál egy comparator kivonó módban?',
 ['Subtracts the side input from the back input','Doubles the signal','Inverts the signal','Delays the signal by two ticks'],['Kivonja az oldalsó bemenetet a hátsóból','Duplázza a jelet','Megfordítja a jelet','Két tickkel késlelteti a jelet'],'mc'],
['Which command changes a world rule such as keepInventory?','Melyik paranccsal állítasz világszabályt, például keepInventory-t?',
 ['/gamerule','/rule','/setrule','/worldsetting'],['/gamerule','/rule','/setrule','/worldsetting'],'mc'],
['What are "spawn chunks"?','Mik azok a „spawn chunks”?',
 ['Chunks near world spawn that stay loaded','The first chunk ever generated','Chunks where mobs spawn fastest','Chunks that contain structures'],['A világ spawnja körüli chunkok, amik betöltve maradnak','A legelsőként generált chunk','Ahol a mobok a leggyorsabban spawnolnak','A struktúrákat tartalmazó chunkok'],'mc'],
['What is the default max-players value in server.properties?','Mi a max-players alapértelmezett értéke a server.properties-ben?',
 ['20','10','100','50'],['20','10','100','50'],'mc'],
['What does the "as" subcommand of /execute change?','Mit változtat meg az /execute „as” alparancsa?',
 ['Which entity runs the command','The position of the command','The dimension','The rotation'],['Hogy melyik entitás futtatja a parancsot','A parancs pozícióját','A dimenziót','A forgatást'],'mc'],

['In JavaScript, what does typeof null return?','JavaScriptben mit ad vissza a typeof null?',
 ['"object"','"null"','"undefined"','"number"'],['"object"','"null"','"undefined"','"number"'],'dev'],
['What is the time complexity of binary search?','Mi a bináris keresés időbonyolultsága?',
 ['O(log n)','O(n)','O(n log n)','O(1)'],['O(log n)','O(n)','O(n log n)','O(1)'],'dev'],
['What does ACID stand for in databases?','Mit jelent az ACID az adatbázisoknál?',
 ['Atomicity, Consistency, Isolation, Durability','Access, Control, Index, Data','Atomic, Cached, Indexed, Distributed','Append, Commit, Insert, Delete'],['Atomicity, Consistency, Isolation, Durability','Access, Control, Index, Data','Atomic, Cached, Indexed, Distributed','Append, Commit, Insert, Delete'],'dev'],
['Which Java keyword prevents a class from being extended?','Melyik Java kulcsszó akadályozza meg, hogy egy osztályt kiterjesszenek?',
 ['final','static','private','abstract'],['final','static','private','abstract'],'dev'],
['What does CORS protect against?','Mi ellen véd a CORS?',
 ['Unauthorised cross-origin requests','SQL injection','Denial of service','Password reuse'],['Jogosulatlan cross-origin kérések ellen','SQL injection ellen','Szolgáltatásmegtagadás ellen','Jelszó-újrahasználat ellen'],'dev'],
['What does git rebase do?','Mit csinál a git rebase?',
 ['Replays commits on top of a new base','Deletes the commit history','Creates a new remote','Reverts the last merge'],['Újrajátssza a commitokat egy új alapra','Törli a commit-történetet','Új remote-ot hoz létre','Visszavonja az utolsó merge-öt'],'dev'],
['What is "tree shaking" in a JavaScript bundler?','Mi a „tree shaking” egy JavaScript bundlerben?',
 ['Removing code that is never used','Renaming variables to be shorter','Splitting the bundle into chunks','Caching modules between builds'],['A soha nem használt kód eltávolítása','A változónevek rövidítése','A bundle darabolása','Modulok gyorsítótárazása buildek között'],'dev'],
['Which Bukkit event fires when a player breaks a block?','Melyik Bukkit event sül el, amikor egy játékos elbont egy blokkot?',
 ['BlockBreakEvent','PlayerBreakEvent','BlockDestroyEvent','BreakBlockEvent'],['BlockBreakEvent','PlayerBreakEvent','BlockDestroyEvent','BreakBlockEvent'],'dev'],
['What is the hexadecimal value of the decimal number 255?','Mi a 255-ös decimális szám hexadecimális értéke?',
 ['FF','AA','99','F0'],['FF','AA','99','F0'],'dev'],
['Which HTTP header controls how long a browser caches a response?','Melyik HTTP fejléc szabályozza, meddig gyorsítótárazza a böngésző a választ?',
 ['Cache-Control','Set-Cookie','Accept-Encoding','Referer'],['Cache-Control','Set-Cookie','Accept-Encoding','Referer'],'dev'],
['What is the main improvement of HTTP/2 over HTTP/1.1?','Mi a HTTP/2 fő előnye a HTTP/1.1-hez képest?',
 ['Multiplexing many requests over one connection','Built-in encryption','Smaller image formats','Automatic retries'],['Több kérés multiplexelése egyetlen kapcsolaton','Beépített titkosítás','Kisebb képformátumok','Automatikus újrapróbálkozás'],'dev'],
['What is a race condition?','Mi az a race condition?',
 ['A bug where the result depends on the timing of concurrent operations','A loop that never ends','A memory leak in a long-running process','An unhandled network timeout'],['Olyan hiba, ahol az eredmény a párhuzamos műveletek időzítésétől függ','Egy végtelen ciklus','Memóriaszivárgás hosszan futó folyamatban','Kezeletlen hálózati időtúllépés'],'dev'],
['Which character encoding can represent virtually every written character?','Melyik karakterkódolás képes gyakorlatilag minden írásjelet ábrázolni?',
 ['UTF-8','ASCII','ISO-8859-2','Windows-1252'],['UTF-8','ASCII','ISO-8859-2','Windows-1252'],'dev'],
['Which HTTP status class does not exist?','Melyik HTTP státuszosztály nem létezik?',
 ['6xx','2xx','4xx','5xx'],['6xx','2xx','4xx','5xx'],'dev'],
['What does the CSS z-index need in order to take effect?','Mire van szüksége a CSS z-indexnek, hogy hasson?',
 ['A positioned element','A fixed width','An opacity below 1','A flex container'],['Pozicionált elemre','Fix szélességre','1-nél kisebb opacity-re','Flex konténerre'],'dev'],

['Which is the smallest country in the world by area?','Melyik a világ legkisebb országa területre nézve?',
 ['Vatican City','Monaco','San Marino','Liechtenstein'],['Vatikán','Monaco','San Marino','Liechtenstein'],'gen'],
['In which year was Minecraft Alpha released?','Melyik évben jelent meg a Minecraft Alpha?',
 ['2010','2009','2011','2012'],['2010','2009','2011','2012'],'gen'],
['Which organelle is called the powerhouse of the cell?','Melyik sejtszervecskét hívják a sejt erőművének?',
 ['The mitochondrion','The ribosome','The nucleus','The Golgi apparatus'],['A mitokondriumot','A riboszómát','A sejtmagot','A Golgi-készüléket'],'gen'],
['Who developed the theory of general relativity?','Ki dolgozta ki az általános relativitáselméletet?',
 ['Albert Einstein','Isaac Newton','Niels Bohr','Max Planck'],['Albert Einstein','Isaac Newton','Niels Bohr','Max Planck'],'gen'],
['Which Hungarian inventor is credited with the ballpoint pen?','Melyik magyar feltalálóhoz kötik a golyóstollat?',
 ['László Bíró','Ernő Rubik','Kálmán Kandó','Donát Bánki'],['Bíró Lászlóhoz','Rubik Ernőhöz','Kandó Kálmánhoz','Bánki Donáthoz'],'gen'],
['How many time zones does the contiguous United States span?','Hány időzónát ölel fel az Egyesült Államok összefüggő területe?',
 ['4','3','5','6'],['4','3','5','6'],'gen'],
['Which river is usually considered the longest in the world?','Melyiket tartják általában a világ leghosszabb folyójának?',
 ['The Nile','The Danube','The Mississippi','The Yangtze'],['A Nílust','A Dunát','A Mississippit','A Jangcét'],'gen'],
['Which Hungarian city is known as the "city of sunshine"?','Melyik magyar várost hívják a „napfény városának”?',
 ['Szeged','Pécs','Eger','Győr'],['Szegedet','Pécset','Egert','Győrt'],'gen'],
['What is the sum of the interior angles of a triangle?','Mennyi egy háromszög belső szögeinek összege?',
 ['180 degrees','360 degrees','90 degrees','270 degrees'],['180 fok','360 fok','90 fok','270 fok'],'gen'],
['Which planet in our Solar System rotates almost on its side?','A Naprendszer melyik bolygója forog szinte az oldalán?',
 ['Uranus','Neptune','Saturn','Venus'],['Az Uránusz','A Neptunusz','A Szaturnusz','A Vénusz'],'gen'],

['What is the maximum light level in Minecraft?','Mi a maximális fényszint a Minecraftban?',
 ['15','16','10','20'],['15','16','10','20'],'mc'],
['What is the maximum strength of a redstone signal?','Mi a redstone jel maximális erőssége?',
 ['15','16','8','20'],['15','16','8','20'],'mc'],
['How many item slots does a double chest have?','Hány tárgyhely van egy dupla ládában?',
 ['54','52','64','48'],['54','52','64','48'],'mc'],
['What does the tilde (~) mean in a Minecraft command?','Mit jelent a hullámjel (~) egy Minecraft parancsban?',
 ['A coordinate relative to the executor','An exact world coordinate','A wildcard for any player','A comment'],['A végrehajtóhoz képesti relatív koordinátát','Pontos világkoordinátát','Bármelyik játékost jelölő helyettesítőt','Megjegyzést'],'mc'],
['What is the distance ratio between the Nether and the Overworld?','Mennyi a távolságarány a Nether és az Overworld között?',
 ['1 to 8','1 to 4','1 to 16','1 to 2'],['1 a 8-hoz','1 a 4-hez','1 a 16-hoz','1 a 2-höz'],'mc'],
['How far can an enderman teleport at most?','Legfeljebb milyen messzire teleportál egy enderman?',
 ['32 blocks','16 blocks','64 blocks','8 blocks'],['32 blokkra','16 blokkra','64 blokkra','8 blokkra'],'mc'],
['Which enchantment freezes water so you can walk on it?','Melyik varázslat fagyasztja meg a vizet, hogy rá lehessen lépni?',
 ['Frost Walker','Depth Strider','Aqua Affinity','Soul Speed'],['Frost Walker','Depth Strider','Aqua Affinity','Soul Speed'],'mc'],
['How many blocks can one piston push at once?','Hány blokkot tud egy piston egyszerre tolni?',
 ['12','16','8','10'],['12','16','8','10'],'mc'],
['What does the Curse of Binding do?','Mit csinál a Curse of Binding?',
 ['Stops you taking the armour off','Stops the item being enchanted','Makes the item vanish on death','Halves the item durability'],['Nem engedi levenni a páncélt','Nem engedi elvarázsolni a tárgyat','Halálkor eltünteti a tárgyat','Felezi a tárgy tartósságát'],'mc'],

['What is the default character encoding of HTML5?','Mi a HTML5 alapértelmezett karakterkódolása?',
 ['UTF-8','ASCII','ISO-8859-1','UTF-16'],['UTF-8','ASCII','ISO-8859-1','UTF-16'],'dev'],
['What is a closure in JavaScript?','Mi az a closure JavaScriptben?',
 ['A function that keeps access to the scope it was created in','A loop that closes over an array','A way to end a script early','A private class field'],['Olyan függvény, ami megtartja a hozzáférést a létrehozási hatóköréhez','Tömbön záródó ciklus','A szkript korai lezárásának módja','Privát osztálymező'],'dev'],
['What is memoization?','Mi az a memoizáció?',
 ['Caching a function\'s result for the same inputs','Storing data in the browser','Writing memory to disk','Reordering a loop'],['Egy függvény eredményének gyorsítótárazása azonos bemenetre','Adattárolás a böngészőben','A memória lemezre írása','Egy ciklus átrendezése'],'dev'],
['What is the complexity of two nested loops over n items?','Mi a bonyolultsága két egymásba ágyazott ciklusnak n elemen?',
 ['O(n²)','O(n)','O(log n)','O(2ⁿ)'],['O(n²)','O(n)','O(log n)','O(2ⁿ)'],'dev'],
['What does a load balancer do?','Mit csinál egy load balancer?',
 ['Spreads traffic across several servers','Compresses responses','Caches images','Encrypts passwords'],['Elosztja a forgalmat több szerver között','Tömöríti a válaszokat','Gyorsítótárazza a képeket','Titkosítja a jelszavakat'],'dev'],
['Which SQL clause filters rows after GROUP BY?','Melyik SQL kulcsszó szűri a sorokat a GROUP BY után?',
 ['HAVING','WHERE','ORDER BY','LIMIT'],['HAVING','WHERE','ORDER BY','LIMIT'],'dev'],
['What does the defer attribute do on a script tag?','Mit csinál a defer attribútum egy script tagen?',
 ['Runs the script after the HTML has been parsed','Loads the script twice','Blocks rendering until it finishes','Skips the script on mobile'],['A HTML feldolgozása után futtatja a szkriptet','Kétszer tölti be a szkriptet','Blokkolja a renderelést, amíg lefut','Mobilon kihagyja a szkriptet'],'dev'],
['What is a polyfill?','Mi az a polyfill?',
 ['Code that supplies a feature an older browser lacks','A CSS background pattern','A minified stylesheet','A database migration'],['Kód, ami pótol egy funkciót, ami a régi böngészőből hiányzik','Egy CSS háttérminta','Egy minifikált stíluslap','Egy adatbázis-migráció'],'dev'],
['In an IP packet, what does TTL limit?','Egy IP csomagnál mit korlátoz a TTL?',
 ['How many hops it may take','How many bytes it may carry','How long the connection stays open','How many retries are allowed'],['Hány ugrást tehet meg','Hány bájtot vihet','Meddig marad nyitva a kapcsolat','Hányszor próbálkozhat újra'],'dev'],
['What is the key difference between a process and a thread?','Mi a fő különbség egy folyamat és egy szál között?',
 ['Threads share memory inside one process','Threads always run on separate machines','Processes cannot use the CPU','Threads cannot be interrupted'],['A szálak közös memórián osztoznak egy folyamaton belül','A szálak mindig külön gépen futnak','A folyamatok nem használhatják a CPU-t','A szálakat nem lehet megszakítani'],'dev'],

['What is the atomic number of carbon?','Mi a szén rendszáma?',
 ['6','12','8','14'],['6','12','8','14'],'gen'],
['Who was the first person in space?','Ki volt az első ember az űrben?',
 ['Yuri Gagarin','Neil Armstrong','Alan Shepard','John Glenn'],['Jurij Gagarin','Neil Armstrong','Alan Shepard','John Glenn'],'gen'],
['Which is the longest bone in the human body?','Melyik a leghosszabb csont az emberi testben?',
 ['The femur','The tibia','The humerus','The spine'],['A combcsont','A sípcsont','A felkarcsont','A gerinc'],'gen'],
['In which year was the World Wide Web opened to the public?','Melyik évben vált a World Wide Web nyilvánossá?',
 ['1991','1989','1995','1993'],['1991','1989','1995','1993'],'gen'],
['Which gas makes up most of Earth\'s atmosphere?','Melyik gáz alkotja a Föld légkörének nagy részét?',
 ['Nitrogen','Oxygen','Carbon dioxide','Argon'],['A nitrogén','Az oxigén','A szén-dioxid','Az argon'],'gen'],
['How many time zones does Russia span?','Hány időzónát ölel fel Oroszország?',
 ['11','9','7','13'],['11','9','7','13'],'gen'],
['Which is the smallest bone in the human body?','Melyik a legkisebb csont az emberi testben?',
 ['The stapes, in the ear','The kneecap','The coccyx','The floating rib'],['A kengyel, a fülben','A térdkalács','A farokcsont','A lebegő borda'],'gen'],
['Which Hungarian mathematician gave his name to a collaboration "number"?','Melyik magyar matematikusról neveztek el egy együttműködési „számot”?',
 ['Paul Erdős','John von Neumann','Frigyes Riesz','Farkas Bolyai'],['Erdős Pálról','Neumann Jánosról','Riesz Frigyesről','Bolyai Farkasról'],'gen']
]
};
